name: env-gobal
on: push

jobs: # 우선순위 레포가 더높다 (org보다)
  get-evn:
    runs-on: ubuntu-latest
    steps:
      - name: check env & secrets
        run:  |
          echo ${{ vars.vari }} 
          echo ${{ secrets.abc }}

  get-env-dev: #레포 내에 환경(공간) 을 따로만들어서 거기서 또 지정가능
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: dev env
        run: |
          echo ${{ secrets.sekey }}
          echo ${{ vars.vakey }}