name: matrix
on: push

jobs:
  get-matrix:
    strategy:
      matrix:
        os: [macos-latest, unbuntu-latest]
        version: [12,14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: chek matrix
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.version }}