# 왜사용할까 더유연한 워크플로우를 만들기 위해
name: contxet
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJSON(github) }}'
      - name: git context check
        run: |
          echo ${{ github.repository }}
          echo ${{ github.event_name }}